name: Pipeline de Compilação e Teste

# Definindo os gatilhos para acionar o pipeline
on:
  push:
    branches:
      - main  # Executar o pipeline quando houver push na branch main

# Definição das etapas do pipeline
jobs:
  build:
    runs-on: ubuntu-latest  # Usar uma máquina Ubuntu para compilar e testar o projeto

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x' 

    - name: Restaurar dependências
      run: dotnet restore ./TempMotoWeb/TempMotoWeb.csproj

    - name: Compilar o código
      run: dotnet build --configuration Release ./TempMotoWeb/TempMotoWeb.csproj

    - name: Executar testes
      run: dotnet test --configuration Release ./TempMotoWeb/TempMotoWeb.csproj
