name: Pipeline de Esteira para Projeto

# Definindo os gatilhos para acionar o pipeline
on:
  push:
    branches:
      - main  # Executar o pipeline quando houver push na branch main

# Definição das etapas do pipeline
jobs:
  build:
    runs-on: ubuntu-latest  # Usar uma máquina Ubuntu para construir o projeto

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'  # Especifique a versão do .NET Core SDK que deseja usar

    - name: Restaurar dependências
      run: dotnet restore ./TempMotoWeb/TempMotoWeb.csproj

    - name: Compilar o código
      run: dotnet build --configuration Release ./TempMotoWeb/TempMotoWeb.csproj

    - name: Executar testes
      run: dotnet test --configuration Release ./TempMotoWeb/TempMotoWeb.csproj

    - name: Publicar artefatos
      uses: actions/upload-artifact@v2
      with:
        name: Esteirado-Artefatos-Build
        path: ./TempMotoWeb/bin/Release/net7.0  # Ajuste o caminho conforme necessário
