name: Pipeline de Esteira para Projeto

# Definindo os gatilhos para acionar o pipeline
on:
  push:
    branches:
      - main  # Executar o pipeline quando houver push na branch main

# Definição das etapas do pipeline
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'  # Especifique a versão do .NET Core SDK que deseja usar

    - name: Restaurar dependências
      run: dotnet restore

    - name: Compilar o código
      run: dotnet build --configuration Release --no-restore

    - name: Executar testes
      run: dotnet test --configuration Release --no-restore

    - name: Publicar artefatos
      uses: actions/upload-artifact@v2
      with:
        name: Esteirado-Artefatos-Build
        path: ./TempMotoWeb  # Atualize com o caminho do diretório do seu aplicativo

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Baixar artefatos do build
      uses: actions/download-artifact@v2
      with:
        name: Esteirado-Artefatos-Build

    - name: Implantação no servidor
      # Script para se conectar ao servidor via SSH e implantar o aplicativo
      run: |
        ssh user@your-server 'cd /path/to/TempMotoWeb && dotnet publish -c Release && pm2 restart app'
