name: Pipeline de Esteira para Projeto

# Definindo os gatilhos para acionar o pipeline
on:
  push:
    branches:
      - main  # Executa quando tiver um push

# Definição das etapas do pipeline
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'  # Versão do .NET

    - name: Restaurar dependências
      run: dotnet restore

    - name: Compilar o código
      run: dotnet build --configuration Release ./TempMotoWeb/TempMotoWeb.csproj

    - name: Executar testes
      run: dotnet test --configuration Release ./TempMotoWeb/TempMotoWeb.csproj

    - name: Publicar artefatos
      uses: actions/upload-artifact@v2
      with:
        name: Esteirado-Artefatos-Build
        path: ./TempMotoWeb/bin/Release/net5.0  # Ajuste o caminho conforme necessário

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Baixar artefatos do build
      uses: actions/download-artifact@v2
      with:
        name: Esteirado-Artefatos-Build

    - name: Implantação no servidor
      # Script para se conectar ao servidor via SSH e implantar o aplicativo
      run: |
        ssh user@your-server 'cd /path/to/TempMotoWeb && dotnet publish -c Release && pm2 restart app'
